apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "self-hosted-runner"
  namespace: "<your-team>"
  labels:
    team: "<your-team>"
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  preStopHook: /opt/unregister-runner.sh
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  accessPolicy:
    outbound:
      external:
        # these are the hosts that the runner communicates with
        - host: github.com
        - host: api.github.com
        - host: "*.actions.githubusercontent.com"
        - host: github-releases.githubusercontent.com
        - host: github-registry-files.githubusercontent.com
        - host: codeload.github.com
        - host: pkg-cache.githubusercontent.com
        - host: pkg-containers.githubusercontent.com
        - host: pkg-containers-az.githubusercontent.com
        - host: "*.pkg.github.com"
        - host: "*.s3.amazonaws.com"
  env:
    - name: ENVOY_ADMIN_API
      value: http://127.0.0.1:15000
    - name: ISTIO_QUIT_API
      value: http://127.0.0.1:15020
    - name: GITHUB_REPO
      value: "(navikt|nais)/<your-repo-here>"
    # this must be a github token with rights to register the runner
    - name: GITHUB_PAT
      value: {{ githubPat }}
