name: Release

on:
  push:
    tags:
      - '[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF##*/}" >> $GITHUB_ENV
    - run: docker build -t $IMAGE .
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker push $IMAGE
